"""fix(users): move username in users to user_infos

Revision ID: 197988cb6dcc
Revises: 89f5b3a2b7b4
Create Date: 2026-01-05 21:57:25.081199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '197988cb6dcc'
down_revision: Union[str, Sequence[str], None] = '89f5b3a2b7b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('user_info', 'username')
    # ### end Alembic commands ###
