"""add tables after merging

Revision ID: 218da6a761be
Revises: 670fd44034f5
Create Date: 2025-12-31 23:48:32.547845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '218da6a761be'
down_revision: Union[str, Sequence[str], None] = '670fd44034f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_words', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.drop_column('vocabs', 'review_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vocabs', sa.Column('review_status', postgresql.ENUM('NEWBIE', 'SPECIALIST', 'EXPERT', 'MASTER', name='review_status_enum'), autoincrement=False, nullable=True))
    op.drop_column('user_words', 'category')
    # ### end Alembic commands ###
