"""feat(report): add reports tables

Revision ID: 57a7d9d6f9c4
Revises: 97e4a83debe8
Create Date: 2026-01-01 15:47:34.951778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57a7d9d6f9c4'
down_revision: Union[str, Sequence[str], None] = '97e4a83debe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_sections', 'updated_at')
    op.drop_index(op.f('ix_lessons_status'), table_name='lessons')
    op.drop_column('lessons', 'updated_at')
    op.drop_column('lessons', 'status')
    op.drop_index(op.f('ix_post_comments_status'), table_name='post_comments')
    op.drop_column('post_comments', 'updated_at')
    op.drop_column('post_comments', 'status')
    op.drop_index(op.f('ix_posts_status'), table_name='posts')
    op.drop_column('posts', 'updated_at')
    op.drop_column('posts', 'status')
    op.drop_column('questions', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('status', postgresql.ENUM('PENDING', 'ACCEPTED', 'DECLINED', 'FLAGGED', 'ARCHIVED', name='post_status_enum'), server_default=sa.text("'PENDING'::post_status_enum"), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_posts_status'), 'posts', ['status'], unique=False)
    op.add_column('post_comments', sa.Column('status', postgresql.ENUM('PENDING', 'ACCEPTED', 'DECLINED', 'FLAGGED', name='comment_status_enum'), server_default=sa.text("'PENDING'::comment_status_enum"), autoincrement=False, nullable=False))
    op.add_column('post_comments', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_post_comments_status'), 'post_comments', ['status'], unique=False)
    op.add_column('lessons', sa.Column('status', postgresql.ENUM('DRAFT', 'PENDING', 'PUBLISHED', 'ARCHIVED', 'REJECTED', name='lesson_status_enum'), server_default=sa.text("'DRAFT'::lesson_status_enum"), autoincrement=False, nullable=False))
    op.add_column('lessons', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_lessons_status'), 'lessons', ['status'], unique=False)
    op.add_column('lesson_sections', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
