"""add(database): add table user_info to database - 1 user - 1 info 

Revision ID: 5bd2cdf41ec5
Revises: 10af35c1a5ac
Create Date: 2025-12-31 11:30:49.780451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5bd2cdf41ec5'
down_revision: Union[str, Sequence[str], None] = '10af35c1a5ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', 'OTHER', 'UNDISCLOSED', name='sex_enum'), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('email_alternate', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_info_full_name'), 'user_info', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_info_user_id'), 'user_info', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_info_user_id'), table_name='user_info')
    op.drop_index(op.f('ix_user_info_full_name'), table_name='user_info')
    op.drop_table('user_info')
    # ### end Alembic commands ###
