"""fix: add created_by in lesson, topics and many related tables for posting new lessons

Revision ID: 5ebbf9779daf
Revises: 8c1e2a9f4b7d
Create Date: 2026-01-02 11:51:06.063679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ebbf9779daf'
down_revision: Union[str, Sequence[str], None] = '8c1e2a9f4b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_sections', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_lesson_sections_created_by'), 'lesson_sections', ['created_by'], unique=False)
    op.create_foreign_key(None, 'lesson_sections', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.add_column('lessons', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('lessons', sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'PUBLISHED', 'ARCHIVED', 'REJECTED', name='lesson_status_enum'), nullable=True))
    op.create_index(op.f('ix_lessons_created_by'), 'lessons', ['created_by'], unique=False)
    op.create_foreign_key(None, 'lessons', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.add_column('posts', sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'FLAGGED', 'ARCHIVED', name='post_status_enum'), nullable=True))
    op.add_column('questions', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_questions_created_by'), 'questions', ['created_by'], unique=False)
    op.create_foreign_key(None, 'questions', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.add_column('topics', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_topics_created_by'), 'topics', ['created_by'], unique=False)
    op.create_foreign_key(None, 'topics', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.drop_index(op.f('ix_topics_created_by'), table_name='topics')
    op.drop_column('topics', 'created_by')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_index(op.f('ix_questions_created_by'), table_name='questions')
    op.drop_column('questions', 'created_by')
    op.drop_column('posts', 'status')
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_index(op.f('ix_lessons_created_by'), table_name='lessons')
    op.drop_column('lessons', 'status')
    op.drop_column('lessons', 'created_by')
    op.drop_constraint(None, 'lesson_sections', type_='foreignkey')
    op.drop_index(op.f('ix_lesson_sections_created_by'), table_name='lesson_sections')
    op.drop_column('lesson_sections', 'created_by')
    # ### end Alembic commands ###
