"""create user lesson, vocab tablles

Revision ID: 6231d684203c
Revises: a76e06a331b8
Create Date: 2025-12-30 10:18:53.730673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6231d684203c'
down_revision: Union[str, Sequence[str], None] = 'a76e06a331b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create parent tables first, then children to avoid FK issues
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_order_index'), 'topics', ['order_index'], unique=False)

    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('READING', 'LISTENING', 'SPEAKING', 'WRITING', 'VOCABULARY', 'GRAMMAR', 'TEST', name='lesson_type_enum'), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('audio_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_order_index'), 'lessons', ['order_index'], unique=False)

    op.create_table('lesson_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_sections_order_index'), 'lesson_sections', ['order_index'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('MCQ', 'MULTIPLE_SELECT', 'TRUE_FALSE', 'FILL_IN_THE_BLANK', 'MATCHING', 'ORDERING', 'PRONUNCIATION', 'TRANSCRIPT', name='question_type_enum'), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correct_answer', sa.JSON(), nullable=True),
    sa.Column('audio_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['lesson_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_order_index'), 'questions', ['order_index'], unique=False)

    op.create_table('vocabs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('audio_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('review_status', sa.Enum('NEWBIE', 'SPECIALIST', 'EXPERT', 'MASTER', name='review_status_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabs_word'), 'vocabs', ['word'], unique=True)

    op.create_table('user_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_status', sa.Enum('NEWBIE', 'SPECIALIST', 'EXPERT', 'MASTER', name='review_status_enum'), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('next_reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['vocabs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_words_user_id'), 'user_words', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_words_word_id'), 'user_words', ['word_id'], unique=False)

    op.create_table('user_xp_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.Enum('LESSON_COMPLETE', 'STREAK_BONUS', 'DAILY_QUEST', 'PERFECT_SCORE', 'REFERRAL_BONUS', name='activity_type_enum'), nullable=True),
    sa.Column('xp_amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_xp_log_user_id'), 'user_xp_log', ['user_id'], unique=False)

    # Alter existing tables and create additional indexes
    # Ensure the new Postgres enum type exists before altering the column
    role_type_enum = postgresql.ENUM('ADMIN', 'MODERATOR', 'LEARNER', name='role_type_enum')
    role_type_enum.create(op.get_bind(), checkfirst=True)
    # Use USING cast to convert existing values to the new enum type
    op.execute("""
    ALTER TABLE roles
    ALTER COLUMN type TYPE role_type_enum
    USING type::text::role_type_enum;
    """)
    op.alter_column('roles', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.alter_column('users', 'firebase_uid',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=320),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_firebase_uid_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_firebase_uid_key'), 'users', ['firebase_uid'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'email',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=sa.VARCHAR(length=320),
               existing_nullable=True)
    op.alter_column('users', 'firebase_uid',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.alter_column('roles', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    # Convert back to the original enum type using USING cast
    op.execute("""
    ALTER TABLE roles
    ALTER COLUMN type TYPE roletype
    USING type::text::roletype;
    """)
    # Drop the temporary enum type created during upgrade
    role_type_enum = postgresql.ENUM('ADMIN', 'MODERATOR', 'LEARNER', name='role_type_enum')
    role_type_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_questions_order_index'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_lesson_sections_order_index'), table_name='lesson_sections')
    op.drop_table('lesson_sections')
    op.drop_index(op.f('ix_user_xp_log_user_id'), table_name='user_xp_log')
    op.drop_table('user_xp_log')
    op.drop_index(op.f('ix_user_words_word_id'), table_name='user_words')
    op.drop_index(op.f('ix_user_words_user_id'), table_name='user_words')
    op.drop_table('user_words')
    op.drop_index(op.f('ix_lessons_order_index'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_vocabs_word'), table_name='vocabs')
    op.drop_table('vocabs')
    op.drop_index(op.f('ix_topics_order_index'), table_name='topics')
    op.drop_table('topics')
    # ### end Alembic commands ###
