"""add(table): add tables related with progress

Revision ID: 670fd44034f5
Revises: 5bd2cdf41ec5
Create Date: 2025-12-31 15:20:39.735040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '670fd44034f5'
down_revision: Union[str, Sequence[str], None] = '5bd2cdf41ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
