"""fix: add is_deleted to all tables related with lessons, to provide soft delete or hide lesson in frontend

Revision ID: 81633b7bea3d
Revises: 5ebbf9779daf
Create Date: 2026-01-02 12:25:00.308855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = '81633b7bea3d'
down_revision: Union[str, Sequence[str], None] = '5ebbf9779daf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_sections', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=text('false')))
    op.add_column('lessons', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=text('false')))
    op.add_column('questions', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=text('false')))
    op.add_column('topics', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'is_deleted')
    op.drop_column('questions', 'is_deleted')
    op.drop_column('lessons', 'is_deleted')
    op.drop_column('lesson_sections', 'is_deleted')
    # ### end Alembic commands ###
