"""fix(question): remove lesson_id attribute in question (this is redundant)

Revision ID: 89f5b3a2b7b4
Revises: b5c52de7e25a
Create Date: 2026-01-03 11:21:24.464327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89f5b3a2b7b4'
down_revision: Union[str, Sequence[str], None] = 'b5c52de7e25a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('daily_missions', sa.Column('lesson_type', sa.Enum('READING', 'LISTENING', 'SPEAKING', 'WRITING', 'VOCABULARY', 'GRAMMAR', 'TEST', name='lesson_type_enum'), nullable=True))
    # op.alter_column('daily_missions', 'type',
    #            existing_type=postgresql.ENUM('COMPLETE_SECTION', 'COMPLETE_SECTION_SCORE_80', 'COMPLETE_SECTION_SCORE_90', 'SAVE_WORD', 'REVIEW_FLASHCARD', 'COMPLETE_LISTENING', 'COMPLETE_WRITING', 'COMPLETE_SPEAKING', 'COMPLETE_READING', 'COMPLETE_VOCABULARY', 'COMPLETE_GRAMMAR', name='mission_type_enum'),
    #            nullable=True)
    # op.drop_index(op.f('ix_questions_lesson_id'), table_name='questions')
    # op.drop_constraint(op.f('questions_lesson_id_fkey'), 'questions', type_='foreignkey')
    op.drop_column('questions', 'lesson_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # op.create_foreign_key(op.f('questions_lesson_id_fkey'), 'questions', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    # op.create_index(op.f('ix_questions_lesson_id'), 'questions', ['lesson_id'], unique=False)
    # op.alter_column('daily_missions', 'type',
    #            existing_type=postgresql.ENUM('COMPLETE_SECTION', 'COMPLETE_SECTION_SCORE_80', 'COMPLETE_SECTION_SCORE_90', 'SAVE_WORD', 'REVIEW_FLASHCARD', 'COMPLETE_LISTENING', 'COMPLETE_WRITING', 'COMPLETE_SPEAKING', 'COMPLETE_READING', 'COMPLETE_VOCABULARY', 'COMPLETE_GRAMMAR', name='mission_type_enum'),
    #            nullable=False)
    # op.drop_column('daily_missions', 'lesson_type')
    # ### end Alembic commands ###
